version: '2'
services:


  # NGINX
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: "app_nginx"
    ports:
      #- "30:30"
      #- "45:45"
      - "80:80"
      #- "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro

  # FRONT
  frontsrv:
    image: auth-front
    container_name: "app_front"
    environment:
      - VIRTUAL_HOST=localhost
      - BACK_HOST=localhost
    ports:
      - "3000:3000"

  # BACK
  back:
    image: back-auth
    container_name: "app_back"
    environment:
      - MONGO_HOST=mongo
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=4567
    depends_on:
      - mongo
    ports:
      - "4567:4567"

  # MONGO
  mongo:
    image: mongo:3.3.6
    container_name: "app_mongo"
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ~/mongo_store/db/data:/data/db:rw

  # DUMP
  mongo_backup:
    image: mongodump
    container_name: "dump_mongo"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - CRON_SCHEDULE=* * * * *
      - DB_NAME=react_app
    volumes:
      - ~/mongo-dump-test:/mongodb-backup:rw
    depends_on:
      - mongo
